### ISSUE TITLE
Napi::Error value out of range

### ISSUE THREAD

**Issue by mdjp** [teletype1/aes67-sender-enhanced#3]
Firstly thank you for this work, I'm hoping it will be just what I need. However when running on MacOS (M2 Ventura). I get the following output 

`sudo node aes67-sender-enhanced.js -a MACOS -d 7 -n "Mac Test" -v -m 192.168.0.255 --address 192.168.0.38 -c 2`

`Selected CoreAudio as audio API.
Selected 192.168.0.38 as network interface
Channel input map from the sound card is [ 0, 1 ]
Selected device Existential Audio Inc.: BlackHole 2ch with  2  input channels

We are trying to put  2  channels on the network
This will require  1  AES67 flow(s).

Selected the following MultiCast Addresses:  [ '192.168.0.255' ]
Selected the following names for the AES67 flows:  [ 'Mac Test-Bank-1' ]
Opening audio stream.
Trying to sync to PTP leader.
Initializing PTP client
Synced to 16-98-9c-ff-fe-64-33-79:0 successfully
Starting SAP annoucements and audio stream.
Resycing PTP and RTP timestamp. Offset was 64840453.125ms.
libc++abi: terminating due to uncaught exception of type Napi::Error: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -3179643600
Abort trap: 6`

Is the error likely to be to do with the M2 architecture?

**Comment by teletype1** [comment]
Hi Matthew - that's certainly possible - I don't have an M1 or M2 around to test it on.  The first thing that stands out to me is the time offset.  I would check and make sure your devices all have the same time set, that is almost 18 hours off - it shouldn't be more than a few milliseconds.  That could be what is causing the C++ library error.

Are you familiar enough with node.js to tell me which line of my script the error is coming from?

best,

matt


---
Dr. Matthew McCabe, Ph.D.
Associate Professor of Audio Technology
Columbus State University - Schwob School of Music
Gaeilge má's féidir, Béarla má's gá.
________________________________
From: Matthew Paradis ***@***.***>
Sent: Thursday, June 29, 2023 12:51
To: teletype1/aes67-sender-enhanced ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [teletype1/aes67-sender-enhanced] Napi::Error value out of range (Issue #3)


Firstly thank you for this work, I'm hoping it will be just what I need. However when running on MacOS (M2 Ventura). I get the following output

sudo node aes67-sender-enhanced.js -a MACOS -d 7 -n "Mac Test" -v -m 192.168.0.255 --address 192.168.0.38 -c 2

`Selected CoreAudio as audio API.
Selected 192.168.0.38 as network interface
Channel input map from the sound card is [ 0, 1 ]
Selected device Existential Audio Inc.: BlackHole 2ch with 2 input channels

We are trying to put 2 channels on the network
This will require 1 AES67 flow(s).

Selected the following MultiCast Addresses: [ '192.168.0.255' ]
Selected the following names for the AES67 flows: [ 'Mac Test-Bank-1' ]
Opening audio stream.
Trying to sync to PTP leader.
Initializing PTP client
Synced to 16-98-9c-ff-fe-64-33-79:0 successfully
Starting SAP annoucements and audio stream.
Resycing PTP and RTP timestamp. Offset was 64840453.125ms.
libc++abi: terminating due to uncaught exception of type Napi::Error: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -3179643600
Abort trap: 6`

Is the error likely to be to do with the M2 architecture?

**Comment by mdjp** [comment]
Thanks for the correct response.  Good spot on the time offset, however this makes it even more confusing as when checking the system time on both machines it is the same, so I wouldn't expect it to be anymore than a few seconds out.  
I am using the software clock rather than hardware if that is likely to be the issue (ptp41 is running in a virtual machine).

I will see if I can work out where the error is being thrown tomorrow.

**Comment by mdjp** [comment]
I have managed to resolve this issue.  I needed to recompile audify on my M2 mac.  After that everything seems to be working perfectly.

**Comment by teletype1** [comment]
That was going to be my next question - what the results of npm install were.  Glad you got it working!  Can you send me a brief description of your PTP clock on your network btw?  I have a Dante card at one site, but for testing it would be nice to have a software solution.
